#!/usr/bin/env python3
"""Build a self-contained copy of index.html for hosts that block CDNs.

index.html is the deliverable and loads Tailwind and FontAwesome from their
CDNs. Some hosts (the Claude Artifact viewer among them) enforce a CSP that
blocks external scripts and stylesheets, allowing only Google Fonts. This
script produces preview.artifact.html, which inlines everything except the
Google Fonts link, so the page renders identically under that policy.

index.html is never modified.

Requires, from the repository root:
    npm i -D tailwindcss@3 @fortawesome/fontawesome-free@6.5.2

Then:
    python3 weston-garages-bath/build-preview.py
"""

import base64
import pathlib
import re
import subprocess
import tempfile

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
SRC = HERE / "index.html"
DEST = HERE / "preview.artifact.html"
MODULES = ROOT / "node_modules"
FA = MODULES / "@fortawesome/fontawesome-free"

# Keep in step with the tailwind.config block inside index.html.
THEME = """module.exports = {
  content: [%r],
  theme: { extend: {
    colors: { ink:'#0B0E13', graphite:'#141A22', steel:'#232B36', haze:'#8D98A8',
              paper:'#F2F4F7', signal:'#FF5A0F', plate:'#FFD400', band:'#0B3EA8' },
    fontFamily: { display:['Archivo','system-ui','sans-serif'],
                  sans:['"IBM Plex Sans"','system-ui','sans-serif'],
                  mono:['"IBM Plex Mono"','ui-monospace','monospace'] }
  }}
}"""

# Only these two faces are used; the rest are dropped to keep the file small.
FACES = {"fa-solid-900", "fa-regular-400"}


def build_tailwind(tmp: pathlib.Path) -> str:
    """Compile the stylesheet the Tailwind CDN would have generated at runtime."""
    config, entry, out = tmp / "tw.config.js", tmp / "in.css", tmp / "out.css"
    config.write_text(THEME % str(SRC))
    entry.write_text("@tailwind base;@tailwind components;@tailwind utilities;")
    subprocess.run(
        ["npx", "tailwindcss", "-c", str(config), "-i", str(entry), "-o", str(out), "--minify"],
        check=True, capture_output=True, cwd=ROOT,
    )
    return out.read_text()


def build_fontawesome() -> str:
    """Inline FontAwesome, embedding the two faces the page actually uses."""
    css = (FA / "css/all.min.css").read_text()

    def embed(match: re.Match) -> str:
        name = match.group(1)
        if name not in FACES:
            return 'src:local("x")'
        data = base64.b64encode((FA / f"webfonts/{name}.woff2").read_bytes()).decode()
        return f'src:url(data:font/woff2;base64,{data}) format("woff2")'

    css = re.sub(r"src:url\(\.\./webfonts/([\w-]+)\.woff2\)[^;}]*", embed, css)
    assert "webfonts/" not in css, "a webfont reference survived"
    return css


def main() -> None:
    src = SRC.read_text(encoding="utf-8")

    with tempfile.TemporaryDirectory() as tmpdir:
        tailwind = build_tailwind(pathlib.Path(tmpdir))
    fontawesome = build_fontawesome()

    # The host supplies doctype, head and body, so take only the page content.
    body = src.split('<body class="bg-ink font-sans text-white antialiased">', 1)[1]
    body = body.rsplit("</body>", 1)[0]

    page_css = re.search(r"<style>(.*?)</style>", src, re.S).group(1)
    gfonts = re.search(r'<link href="https://fonts\.googleapis\.com[^>]*>', src).group(0)

    # The page CSS uses box-drawing characters in its section comments. HTML
    # entities do not decode inside <style>, so fold them to ASCII after
    # checking they only appear in comments, where the exact value is inert.
    outside_comments = re.sub(r"/\*.*?\*/", "", page_css, flags=re.S)
    assert outside_comments.isascii(), "non-ASCII outside a CSS comment: " + repr(
        [c for c in outside_comments if not c.isascii()][:5]
    )
    page_css = re.sub(
        r"/\*.*?\*/",
        lambda m: "".join(c if c.isascii() else "-" for c in m.group(0)),
        page_css, flags=re.S,
    )

    assert tailwind.isascii() and fontawesome.isascii(), "inlined CSS must be ASCII"

    # No <meta charset> of ours survives into the host's head, so escape the
    # markup to numeric entities and the page reads correctly under any
    # declared encoding. Without this, "BA1 4BX" renders as "BA1 4BX".
    body = "".join(c if c.isascii() else f"&#{ord(c)};" for c in body)

    page = f"""<meta charset="utf-8">
<title>Weston Garages Bath</title>
{gfonts}

<!-- Generated by build-preview.py from index.html. Do not edit by hand.
     Tailwind and FontAwesome are inlined because the host blocks CDN requests;
     index.html remains the deliverable and still loads both from their CDNs.
     Placeholders (phone, hours, review count, testimonials) are listed in the
     comment block at the top of index.html. -->

<style>{tailwind}</style>
<style>{fontawesome}</style>
<style>
/* The host composites this page over a ground it paints in the viewer's
   theme, so paint ours explicitly. This design commits to one dark look. */
html, body {{ background: #0B0E13; }}
{page_css}</style>

<div class="bg-ink font-sans text-white antialiased">
{body}
</div>
"""
    assert page.isascii(), "output must be encoding-proof"
    DEST.write_text(page, encoding="utf-8")
    print(f"wrote {DEST.relative_to(ROOT)} ({len(page):,} bytes)")


if __name__ == "__main__":
    main()
